# version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-javablog
    restart: always
    environment:
      MYSQL_DATABASE: db_javablog
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - ./dump-db_javablog.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: java-blog-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_javablog
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
